title: "T e a P A C S"
description: International Workshop on Teaching Performance Analysis of Computer Systems

# Change this to the year which shall appear as "default" in the website
current_year: 2024

# The following array is used to populate previous editions.
# If the edition is hosted by this site, a corresponding _20xx
# folder is expected to be found, and `output: true` should be set.
# Otherwise, `site` should point to the previous webpage (if available).
# `proceedings` should point to the digital library page of the proceedings (if available).
# `venue`, `location`, and `dates` allow to customize the edition website. The current
# markdown files rely on them throughout the text, so if you clone the content of a past
# edition and set these variables correctly, a good part of the site is already consistent.
collections:
  '2024':
    output: true
    permalink: /:collection/:title
    venue: "Venice, Italy"
    location: "San Servolo Congress Center"
    dates: "June 14, 2024"
  '2023':
    output: true
    permalink: /:collection/:title
    venue: "Orlando, FL, USA"
    location: "Orlando World Marriott"
    dates: "June 19, 2023"
  '2021':
    output: true
    permalink: /:collection/:title
    venue: "Milano, Italy"
    location: Politecnico Di Milano
    dates: "November 12, 2021"

# You are not likely expected to touch below this line
exclude: [README.md, LICENSE]

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-relative-links

relative_links:
  enabled:     true
  collections: true

sass:
  style: compressed
