title: "SIGSIM PADS"
description: ACM SIGSIM Conference on Principles of Advanced Discrete Simulation

# Change this to the year which shall appear as "default" in the website
current_year: 2022

# The following array is used to populate previous editions.
# If the edition is hosted by this site, a corresponding _20xx
# folder is expected to be found, and `output: true` should be set.
# Otherwise, `site` should point to the previous webpage (if available).
# `proceedings` should point to the digital library page of the proceedings (if available).
# `venue`, `location`, and `dates` allow to customize the edition website. The current
# markdown files rely on them throughout the text, so if you clone the content of a past
# edition and set these variables correctly, a good part of the site is already consistent.
collections:
  '2022':
    output: true
    permalink: /:collection/:title
    venue: "Atlanta, GA, USA"
    location: "GeorgiaTech"
    dates: "June 1-2, 2022"
  '2021':
    website: https://web.archive.org/web/20210421225351/https://www.acm-sigsim-pads.org/
    venue: "Suffolk, VA, USA"
    dates: "May 31-June 2, 2021"
  '2020':
    proceedings: https://dl.acm.org/doi/proceedings/10.1145/3384441
    website: https://web.archive.org/web/20191228145515/http://www.acm-sigsim-pads.org/
    venue: "Miami, FL, USA"
    dates: "June 15-17, 2020"
  '2019':
    proceedings: https://dl.acm.org/doi/proceedings/10.1145/3316480
    website: https://web.archive.org/web/20190929201841/https://www.acm-sigsim-pads.org/
    venue: "Chicago, IL, USA"
    dates: "June 15-17, 2020"
  '2018':
    proceedings: https://dl.acm.org/citation.cfm?id=3200921
    website: https://web.archive.org/web/20170530085708/http://acm-sigsim-pads.org/
    venue: "Rome, Italy"
    dates: "May 23-25, 2017"
  '2017':
    proceedings: http://dl.acm.org/citation.cfm?id=3064911
    website: https://web.archive.org/web/20170530085708/http://acm-sigsim-pads.org/
    venue: "Singapore"
    dates: "May 24-26, 2017"
  '2016':
    proceedings: https://dl.acm.org/citation.cfm?id=2901378
    website: https://web.archive.org/web/20160504044541/http://www.acm-sigsim-pads.org:80/
    venue: "Banff, AB, Canada"
    dates: "May 15-18, 2016"
  '2015':
    proceedings: https://dl.acm.org/citation.cfm?id=2769458
    website: https://web.archive.org/web/20150406112909/http://www.acm-sigsim-pads.org:80/
    venue: "London, United Kingdom"
    dates: "June 10-12, 2015"
  '2014':
    proceedings: https://dl.acm.org/citation.cfm?id=2601381
    website: https://web.archive.org/web/20140329232454/http://www.acm-sigsim-pads.org:80/
    venue: "Denver, CO, USA"
    dates: "May 18-21, 2014"
  '2013':
    proceedings: https://dl.acm.org/citation.cfm?id=2486092
    website: https://web.archive.org/web/20130218032000/http://www.acm-sigsim-pads.org:80/
    venue: "Montréal, QC, Canada"
    dates: "May 19-22, 2013"
  '2012':
    title: 26th ACM/IEEE/SCS Workshop on Principles of Advanced and Distributed Simulation
    proceedings: https://dl.acm.org/citation.cfm?id=2372596
    website: https://web.archive.org/web/20131028124516/http://pads2012.cis.fiu.edu/
    venue: "Zhangjiajie, China"
    dates: "July 15-19, 2012"
  '2011':
    title: 25th ACM/IEEE/SCS Workshop on Principles of Advanced and Distributed Simulation
    proceedings: https://ieeexplore.ieee.org/xpl/mostRecentIssue.jsp?punumber=5936496
    website: https://sites.google.com/site/pads2011/
    venue: "Nice, France"
    dates: "June 14-17, 2011"
  '2010':
    title: 24th ACM/IEEE/SCS Workshop on Principles of Advanced and Distributed Simulation
    proceedings: https://ieeexplore.ieee.org/xpl/mostRecentIssue.jsp?punumber=5471198
    website: https://web.archive.org/web/20111007015947/http://www.pads-workshop.org/pads2010/
    venue: "Atlanta, GA, USA"
    dates: "May 17-19, 2010"
  '2009':
    title: 23rd ACM/IEEE/SCS Workshop on Principles of Advanced and Distributed Simulation
    proceedings: https://dl.acm.org/citation.cfm?id=1577959
    website: https://web.archive.org/web/20090510001327/http://www.cs.virginia.edu/pads2009/index.htm
    venue: "Lake Placid, NY, USA"
    dates: "June 22-25, 2009"
  '2008':
    title: 22nd ACM/IEEE/SCS Workshop on Principles of Advanced and Distributed Simulation
    proceedings: https://web.archive.org/web/20090403135124/https://www.cis.fiu.edu/pads2008/
    venue: "Rome, Italy"
    dates: "June 3-6, 2008"
  '2007':
    title: 21st ACM/IEEE/SCS Workshop on Principles of Advanced and Distributed Simulation
    proceedings: https://dl.acm.org/citation.cfm?id=1248822
    website: http://pads07.org/
    venue: "San Diego, CA, USA"
    dates: "June 12-15, 2007"
  '2006':
    title: 20th ACM/IEEE/SCS Workshop on Principles of Advanced and Distributed Simulation
    proceedings: https://dl.acm.org/citation.cfm?id=1136644
    website: https://web.archive.org/web/20171117011056/http://pdcc.ntu.edu.sg/pads2006/
    venue: "Singapore"
    dates: "May 24-26, 2006"
  '2005':
    title: 19th ACM/IEEE/SCS Workshop on Principles of Advanced and Distributed Simulation
    proceedings: https://dl.acm.org/citation.cfm?id=1069810
    website: https://web.archive.org/web/20161103151756/http://pads-workshop.org/pads2005/index.html
    venue: "Monterey, CA, USA"
    dates: "June 1-3, 2005"
  '2004':
    title: 18th ACM/IEEE/SCS Workshop on Principles of Advanced and Distributed Simulation
    proceedings: https://dl.acm.org/citation.cfm?id=1013329
    venue: "Kufstein, Austria"
    dates: "May 16-19, 2004"
  '2003':
    title: 17th ACM/IEEE/SCS Workshop on Principles of Advanced and Distributed Simulation
    proceedings: https://dl.acm.org/citation.cfm?id=824475
    website: https://web.archive.org/web/20041215141621/http://pads-workshop.org/pads2003/index.html
    venue: "San Diego, CA, USA"
    dates: "June 10-13, 2003"
  '2002':
    title: 16th ACM/IEEE/SCS Workshop on Principles of Advanced and Distributed Simulation
    proceedings: https://dl.acm.org/citation.cfm?id=564062
    venue: "Arlington, VA, USA"
    dates: "May 12-15, 2002"
  '2001':
    title: 15th Workshop on Parallel and Distributed Simulation
    proceedings: https://dl.acm.org/citation.cfm?id=375658
    venue: "Lake Arrowhead, CA, USA"
    dates: "May 15-18, 2001"
  '2000':
    title: 14th Workshop on Parallel and Distributed Simulation
    proceedings: https://dl.acm.org/citation.cfm?id=336146
    venue: "Bologna, Italy"
    dates: "May 28-31, 2000"
  '1999':
    title: 13th Workshop on Parallel and Distributed Simulation
    proceedings: https://dl.acm.org/citation.cfm?id=301429
    venue: "Atlanta, GA, USA"
    dates: "May 1-4, 1999"
  '1998':
    title: 12th Workshop on Parallel and Distributed Simulation
    proceedings: https://dl.acm.org/citation.cfm?id=278008
    website: https://example.com
    venue: "Banff, AB, Canada"
    dates: "May 26-29, 1998"
  '1997':
    title: 11th Workshop on Parallel and Distributed Simulation
    proceedings: https://dl.acm.org/citation.cfm?id=268826
    venue: "Lockenhaus, Austria"
    dates: "June 10-13, 1997"
  '1996':
    title: 10th Workshop on Parallel and Distributed Simulation
    proceedings: https://dl.acm.org/citation.cfm?id=238788
    venue: "Philadelphia, PA, USA"
    dates: "May 22-24, 1996"
  '1995':
    title: 9th Workshop on Parallel and Distributed Simulation
    proceedings: https://dl.acm.org/citation.cfm?id=214282
    venue: "Lake Placid, NY, USA"
    dates: "June 13-16, 1995"
  '1994':
    title: 8th Workshop on Parallel and Distributed Simulation
    proceedings: https://dl.acm.org/citation.cfm?id=182478
    venue: "Edinburgh, Scotland"
    dates: "July 6-8, 1994"
  '1993':
    title: 7th Workshop on Parallel and Distributed Simulation
    proceedings: https://dl.acm.org/citation.cfm?id=158459
    venue: "San Diego, CA, USA"
    dates: "May 16-19, 1993"
  '1992':
    title: 6th Workshop on Parallel and Distributed Simulation
    proceedings: https://books.google.com/books/about/6th_Workshop_on_Parallel_and_Distributed.html?id=aWE_AQAAIAAJ
    venue: "Newport Beach, CA, USA"
    dates: "January 20-22, 1992"
  '1991':
    title: SCS Multiconference on Advances in Parallel and Distributed Simulation
    proceedings: https://books.google.com/books?id=MawZAQAAIAAJ&source=gbs_similarbooks
    venue: "Anaheim, CA, USA"
    dates: "January 23-25, 1991"
  '1990':
    title: SCS Multiconference on Advances in Parallel and Distributed Simulation
    proceedings: https://books.google.com/books/about/Distributed_simulation.html?id=C6wZAQAAIAAJ
    venue: "San Diego, CA, USA"
    dates: "January 17-19, 1990"
  '1989':
    title: SCS Multiconference on Advances in Parallel and Distributed Simulation
    proceedings: https://books.google.com/books?id=qakZAQAAIAAJ&source=gbs_similarbooks
    venue: "Tampa, CA, USA"
    dates: "March 28-31, 1989"
  '1988':
    title: SCS Multiconference on Advances in Parallel and Distributed Simulation
    proceedings: https://books.google.com/books?id=YtEZAQAAIAAJ&source=gbs_similarbooks
    venue: "San Diego, CA, USA"
    dates: "February 3-5, 1988"
  '1985':
    title: SCS Conference on Distributed Simulation
    venue: "San Diego, CA, USA"
    dates: "January 24-26, 1985"




# You are not likely expected to touch below this line
exclude: [README.md, LICENSE]

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-relative-links

relative_links:
  enabled:     true
  collections: true

sass:
  style: compressed
